version: '3.1'

services:
  textms-db-dev:
      image: mysql
      restart: always
      environment:
        MYSQL_DATABASE: 'dev_textms_db'
        MYSQL_USER: 'dev_textms_db_user'
        MYSQL_PASSWORD: 'dev_textms_db_password'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3333:3306'
      expose:
        # Opens port 3333 on the container
        - '3333'
      command: --character-set-server=utf8 --collation-server=utf8_general_ci